### ISSUE TITLE
Roadmap of your implementation (+ questions)

### ISSUE THREAD

**Issue by yvan-sraka** [SAI-Aghylas/RustProject4IABD#1]
You chose `libray` project: _a fully-featured raytracing library_

Right now you have an implemented based on https://bheisler.github.io/post/writing-raytracer-in-rust-part-1/

I really expect from you to provide:

- **Make the computation parallel**
- **Have a progress bar of the raytracing process and provide large test**

As a bonus can you:

- Handle other 3D formats (currently, your program take a `json`)
- Be able to change the camera position and angle in the scene with the mouse (use OpenGL to display scene while user move mouse)

Question:

- **Is OpenGL use raytracing to render 3D scene? How does this work? What the benefits of both methods?**

- **What is shadering? How is it computed? Why smart people do raytracing in shaders?**

**Comment by merzouk13** [comment]
- **Is OpenGL use raytracing to render 3D scene? How does this work? What the benefits of both methods? :**

No openGl does not use raytracing, but uses rasterization. Rasterizing is very often used to render 3D graphics and this in real time such as those used in video games. Resterization transforms a 3D scene into a 2D scene and this in real time. The way it works is that the rasterizer checks the set of triangles that make up the 3D scene and determines which ones will be visible or not from the current perspective. After that there is an analysis on the light sources as well as other details related to the environment for adding light and colors to the pixels of each triangle. In conclusion, what there is to remember is that rasterization with OpenGL is much faster but remains less realistic unlike raytracing which is quite slow but much more realistic

**Comment by merzouk13** [comment]
**What is shadering? How is it computed? Why smart people do raytracing in shaders?:**
A shader is a small program that runs on a graphics card or GPU that manipulates a 3D scene during the rendering pipeline phase before the image is printed on the screen. With shaders we have the possibility of creating a range of rendering effects and this quickly enough for applications using them in real time such as video games. the papeline phase is made up of four stages which are: -Model transform.
-View transform.
-Project transformation.
-viewport transform. We have two types of shaders: -Vertex shader can manipulate the attributes of vertices which are the corner points of a polygon.
- Fragment shader is computing the color of each pixel.

The reason why smart people do raytracing in shaders may be because it's the best way to do raytracing with parallelism computing and harness the power of GPUs
